let actionConstants  = () => {
	

	return {

		"SET_USER_INFO" : "SET_USER_INFO",
		"SET_USER_LOGGED_IN" : "SET_USER_LOGGED_IN",
		"ADD_NOTIFICATION" : "ADD_NOTIFICATION",
		"SET_NOTIFICATION_TRIGGER_FLAG" : "SET_NOTIFICATION_TRIGGER_FLAG",
		"SET_FLAGS" : "SET_FLAGS",
		"SET_CATEGORIES" : "SET_CATEGORIES",
		"SET_LOCATIONS" : "SET_LOCATIONS",
		"SET_EVENTS" : "SET_EVENTS",
		"SET_POSTS" : "SET_POSTS"
	};

};

export default actionConstants();