let actionConstants  = () => {
	

	return {

		"SET_USER_INFO" : "SET_USER_INFO",
		"SET_USER_LOGGED_IN" : "SET_USER_LOGGED_IN",
		"SET_GAME_STATUS_FLAGS" : "SET_GAME_STATUS_FLAGS",
		"ADD_NEW_LEVEL" : "ADD_NEW_LEVEL",
		"SELECTED_OPTION" : "SELECTED_OPTION",
		"CLEAR_STATUS_FLAGS" : "CLEAR_STATUS_FLAGS",
		"CLEAR_LEVELS" : "CLEAR_LEVELS",
		"ADD_NOTIFICATION" : "ADD_NOTIFICATION",
		"SET_NOTIFICATION_TRIGGER_FLAG" : "SET_NOTIFICATION_TRIGGER_FLAG"


	};

};

export default actionConstants();