MYSQL_DATABASE_USER = 'root'
MYSQL_DATABASE_PASSWORD = ''
MYSQL_DATABASE_DB = 'govol_new'
MYSQL_DATABASE_HOST = 'localhost'
BUCKET="govol1"
SECRET_KEY='A0Zr98j/3yX R~XHH!jmN]LWX/,?RT'
SEND_EMAIL_ID=''